version: "{build}"

clone_folder: c:\gopath\src\github.com\docker\docker-credential-helpers

environment:
    global:
      GOPATH: c:\gopath
      CGO_ENABLED: 1
      MSYS2_BITS: 64

init:
  - git config --global core.autocrlf input

install:
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.7.windows-amd64.msi
  - msiexec /i go1.7.windows-amd64.msi /q
  - set Path=c:\msys64\mingw%MSYS2_BITS%\bin;c:\go\bin;%Path%
  - go version
  - go env

build: false

test_script:
  - go vet ./wincred
  - go test -v github.com/docker/docker-credential-helpers/wincred

after_test:
  - mkdir bin
  - go build -o bin/docker-credential-wincred.exe wincred/cmd/main_windows.go

artifacts:
  - path: bin/docker-credential-wincred.exe
    name: docker-credential-wincred.exe

branches:
  only:
    - master
